### ISSUE TITLE
SIGSEGV if `qovery_container_registry` miss `config`

### ISSUE THREAD

**Issue by spacedub** [Qovery/terraform-provider-qovery#153]
```
resource "qovery_container_registry" "ghcr" {
  # Required
  organization_id = var.organization_id
  name            = "Foo"
  kind            = "PUBLIC_ECR"
  url             = "bar.io"

}
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x1055ddd04]

goroutine 14 [running]:
github.com/qovery/terraform-provider-qovery/qovery.ContainerRegistry.toUpsertRequest({{0x1, 0x0, {0x0, 0x0}}, {0x0, 0x0, {0x140001c63c0, 0x24}}, {0x0, 0x0, ...}, ...})
	github.com/qovery/terraform-provider-qovery/qovery/resource_container_registry_model.go:45 +0xd4
github.com/qovery/terraform-provider-qovery/qovery.containerRegistryResource.Create({{_, _}}, {_, _}, {{{{0x105991f80, 0x14000382180}, {0x10585a580, 0x14000725b90}}, {0x140004b28d0, 0x0, ...}}, ...}, ...)
	github.com/qovery/terraform-provider-qovery/qovery/resource_container_registry.go:154 +0x140
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0x14000228160, {0x10598db40, 0x14000725530}, 0x140007b33e0, 0x140007b3380)
	github.com/hashicorp/terraform-plugin-framework@v0.14.0/internal/fwserver/server_createresource.go:97 +0x540
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0x10598db40?, {0x10598db40, 0x14000725530}, 0x140008065a0, 0x140007b3550)
	github.com/hashicorp/terraform-plugin-framework@v0.14.0/internal/fwserver/server_applyresourcechange.go:54 +0x370
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0x14000228160, {0x10598db40?, 0x140007253e0?}, 0x14000806550)
	github.com/hashicorp/terraform-plugin-framework@v0.14.0/internal/proto6server/server_applyresourcechange.go:52 +0x1a4
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0x1400015a0a0, {0x10598db40?, 0x14000724c00?}, 0x140000e6930)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov6/tf6server/server.go:816 +0x3b8
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x10594b8a0?, 0x1400015a0a0}, {0x10598db40, 0x14000724c00}, 0x140000e6850, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002ca000, {0x105992258, 0x140002949c0}, 0x140007038c0, 0x140002b8c60, 0x105f854c0, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0x9c4
google.golang.org/grpc.(*Server).handleStream(0x140002ca000, {0x105992258, 0x140002949c0}, 0x140007038c0, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x290
```

Points to https://github.com/Qovery/terraform-provider-qovery/blob/main/qovery/resource_container_registry_model.go#L45

where very likely Config is nil.

**Comment by mzottolaqovery** [comment]
Hello @spacedub, 
This issue has been fixed in latest release: [v0.14.4](https://github.com/Qovery/terraform-provider-qovery/releases/tag/v0.14.4)
