### ISSUE TITLE
Provider crash

### ISSUE THREAD

**Issue by arthureichelberger** [Qovery/terraform-provider-qovery#195]
Hey there!

```
[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mPlugin did not respond[0m
[31m│[0m [0m
[31m│[0m [0m[0mThe plugin encountered an error, and failed to respond to the
[31m│[0m [0mplugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
[31m│[0m [0mcontain more details.
[31m╵[0m[0m

Stack trace from the terraform-provider-qovery_v0.15.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xccfb9b]

goroutine 71 [running]:
github.com/qovery/terraform-provider-qovery/qovery.fromGoValueToTfValue({0xd775a0?, 0xc000414ae0?}, {0x0?, 0x0?})
	github.com/qovery/terraform-provider-qovery/qovery/types_conversions.go:263 +0x39b
github.com/qovery/terraform-provider-qovery/qovery.fromStringMap(0xc000244158)
	github.com/qovery/terraform-provider-qovery/qovery/types_conversions.go:302 +0x25d
github.com/qovery/terraform-provider-qovery/qovery.convertResponseToCluster(_)
	github.com/qovery/terraform-provider-qovery/qovery/resource_cluster_model.go:193 +0x3e5
github.com/qovery/terraform-provider-qovery/qovery.clusterResource.Create({_}, {_, _}, {{{{0x10862c8, 0xc0008e09c0}, {0xdd9bc0, 0xc0008d1bf0}}, {0xc000557f80, 0x0, 0x0, ...}}, ...}, ...)
	github.com/qovery/terraform-provider-qovery/qovery/resource_cluster.go:373 +0x16e
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc0002a8160, {0x1081d60, 0xc0008d0f60}, 0xc000161360, 0xc000161300)
	github.com/hashicorp/terraform-plugin-framework@v0.14.0/internal/fwserver/server_createresource.go:97 +0x8ce
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0x1081d60?, {0x1081d60, 0xc0008d0f60}, 0xc00061dd10, 0xc0001614d0)
	github.com/hashicorp/terraform-plugin-framework@v0.14.0/internal/fwserver/server_applyresourcechange.go:54 +0x4a8
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc0002a8160, {0x1081d60?, 0xc0008d0e10?}, 0xc00061dcc0)
	github.com/hashicorp/terraform-plugin-framework@v0.14.0/internal/proto6server/server_applyresourcechange.go:52 +0x27b
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc000194140, {0x1081d60?, 0xc0008d0450?}, 0xc0007873b0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/tf6server/server.go:816 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0xed3480?, 0xc000194140}, {0x1081d60, 0xc0008d0450}, 0xc000787340, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00049e000, {0x10865b8, 0xc0006824e0}, 0xc0008bfe60, 0xc0002008d0, 0x16d67a0, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc00049e000, {0x10865b8, 0xc0006824e0}, 0xc0008bfe60, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-qovery_v0.15.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by mzottolaqovery** [comment]
A fix is in progress

**Comment by mzottolaqovery** [comment]
Fix is done & released in [last version ](https://github.com/Qovery/terraform-provider-qovery/releases/tag/v0.15.1)
Thanks for having reported it

**Comment by benjaminch** [comment]
Closing this one as it should be fixed, please feel free to re-open it if it's not @arthureichelberger
